### ISSUE TITLE
Cast exception when calling increment

### ISSUE THREAD

**Issue by billy1380** [theupswell/appengine-counter#21]
I am getting a cast exception when calling the increment method in some instances

``` java
java.lang.ClassCastException: com.google.appengine.api.datastore.Entity cannot be cast to com.theupswell.appengine.counter.data.CounterData
	at com.theupswell.appengine.counter.service.ShardedCounterServiceImpl$3.run(ShardedCounterServiceImpl.java:904)
	at com.theupswell.appengine.counter.service.ShardedCounterServiceImpl$3.run(ShardedCounterServiceImpl.java:900)
	at com.googlecode.objectify.impl.TransactorYes.transact(TransactorYes.java:102)
	at com.googlecode.objectify.impl.ObjectifyImpl.transact(ObjectifyImpl.java:178)
	at com.theupswell.appengine.counter.service.ShardedCounterServiceImpl.getOrCreateCounterData(ShardedCounterServiceImpl.java:899)
	at com.theupswell.appengine.counter.service.ShardedCounterServiceImpl$IncrementShardWork.run(ShardedCounterServiceImpl.java:447)
	at com.theupswell.appengine.counter.service.ShardedCounterServiceImpl$IncrementShardWork.run(ShardedCounterServiceImpl.java:412)
	at com.googlecode.objectify.impl.TransactorNo.transactOnce(TransactorNo.java:118)
	at com.googlecode.objectify.impl.TransactorNo.transactNew(TransactorNo.java:95)
	at com.googlecode.objectify.impl.TransactorNo.transact(TransactorNo.java:85)
	at com.googlecode.objectify.impl.ObjectifyImpl.transact(ObjectifyImpl.java:178)
	at com.theupswell.appengine.counter.service.ShardedCounterServiceImpl.increment(ShardedCounterServiceImpl.java:389)
```

**Comment by billy1380** [comment]
Objectify best practice (https://github.com/objectify/objectify/wiki/BestPractices) recommends using your own objectify class to ensure entities are registered. This seems to be happening because entities are not registered because counter uses the objectify service provided and relies on the entities already having been registered else where.

It would be good if the ShardedCounterServiceImpl accepted an objectify service. For now I just create a factory that registers the entities before instantiating and returning ShardedCounterServiceImpl.

**Comment by sappenin** [comment]
Hi, thanks for following up on this issue.  Yes, as you pointed out, currently appengine-counter doesn't automatically register its entities for you.  You'll need to manually register them along with your other entities -- a factory like you indicated is the ideal place.  Motomapia (created by Jeff, the creator of objectify) provides a good example: 

https://github.com/stickfigure/motomapia/blob/master/src/main/java/com/motomapia/OfyFactory.java

We don't want ShardedCounterServiceImpl to accept an ObjectifyService in the constructor because this might cause problems.  See here for more details:

[Can I use Dependency Injection with Objectify](https://github.com/objectify/objectify/wiki/FrequentlyAskedQuestions#can-i-use-dependency-injection-spring-guice-weld-with-objectify)

However, thinking about this more, it seems like there's only ever a single ObjectifyFactory floating around, which is where these entities would be registered, so it might make sense to add another constructor to ShardedCounterServiceImpl that requires an ObjectifyFactory.  That way, when you construct the ShardedCounterService (or when you DI system does) appengine-counter could auto-register the entities.  I'll experiment with that to see if it can work.

**Comment by sappenin** [comment]
Closing this as a non-issue, but capturing the enhancement request as part of #23.  Please re-open if this is still an issue for you.
